language: scala

scala:
  - 2.11.8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

jdk:
   - oraclejdk8

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      - secure: "RKa9fAISHO4qSr1RlfCKyzKFtsTVDeorTDNARPa/ebQGaeotpsDgj6pEtuAm7U/k38d0lYZpQmT3ne7S0P4AagTTANYmzPgHz/A4dZ3ysXr523XpSLEYv1uBUpPp5qQJkd9iw7ldFDOs+xiAmhd80gOXAh8C/wr/BANJd52BAc4zg9q54NGdWKu4M7xbEnRIDs5hPvGbfAGx9BKatTCvPKUXk8r+1eXzmC2hwE2y6Kw4fx5dRq6xEa+1EqtQR7QiW4Izju+tzTpQagn1BeMmHDkEYMpjZ6IJP9lRUQ7OL0FTy6ptITt4UTYUM5J35Fq6NTMXxFPmw4wpWLANpA8S37wjpf341ko1UP3vLzVhfRqMfGR9X4d/pSMTJ8zwkID02CbfHw3fNn2KuB0KENpdYc8oMUw//fXSMvGw7Nlvq8xJti91wQnHWqfV2IDfOD4rCc+NiTUOiCP9sOhb1hoU0f7JQ7f4Rka8EWqaZSjw31/EnqJyWa8L+z1AkQM6A2PDc0o18i9SQuZetg98eTAzSAwwpRhtT4UrZjhx+iyYgq/L/CbhHyIFqN21cp52kCXoDn3VsCc73pPM2N+OnX0OtaTM/jaG9ZHGvhl5TIAs2S1G7zyMVIGzKBXijIREOojtCKYvh0MZrxiEYXimUfDi7/FFVLaES7H1MLPGA2gl80c="
    on_success: change
    on_failure: always
  email:
    on_success: change
    on_failure: always