apiVersion: v1
kind: Service
metadata:
  name: baas-state-service
  labels:
    run: baas-state-service
spec:
  selector:
    app: baas-state
  ports:
    - port: 8080
      protocol: TCP
  type: LoadBalancer

# Run this command to expose the service to minikube
# minikube service baas-state-service
